# Google Cloud Run Configuration
# File: cloudbuild.yaml

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fertivision:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fertivision:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fertivision'
      - '--image'
      - 'gcr.io/$PROJECT_ID/fertivision:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '100'
      - '--max-instances'
      - '100'
      - '--set-env-vars'
      - 'FLASK_ENV=production,DATABASE_URL=sqlite:///reproductive_analysis.db'

images:
  - 'gcr.io/$PROJECT_ID/fertivision:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
