#!/bin/bash
# Render.com Deployment Guide for FertiVision

echo "🎨 Render.com - Simple Free Deployment"
echo "======================================"
echo ""
echo "🎯 SIMPLE STEPS:"
echo "1. Go to: https://render.com"
echo "2. Sign up with GitHub"
echo "3. Click 'New' → 'Web Service'"
echo "4. Connect your GitHub repo: fertivision-codelm"
echo "5. Use these settings:"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: python app.py"
echo "   - Auto-Deploy: Yes"
echo ""
echo "✅ BENEFITS:"
echo "- 750 hours/month FREE"
echo "- Auto-deploy from Git"
echo "- Custom domains"
echo "- SSL certificates"
echo "- Good for demos"
echo ""
echo "⚠️ LIMITATION:"
echo "- Spins down after 15min inactivity"
echo "- ~30s cold start time"
echo ""
echo "⚡ DEPLOYMENT TIME: ~3 minutes"
echo "💰 COST: FREE (750 hours/month)"
echo ""
echo "🔗 Quick deploy: https://render.com/new/web"
